language: python
python:
  - "3.6"

install:
  - pip3 install --upgrade setuptools
  - pip3 install -r requirements.txt
  - pip3 install flake8

before_script:
  #  - flake8 --exclude app/dbmodels --exclude fill_db.py app
  - flake8 pythonutils

script:
  - python3 -m unittest -v tests/test_simple.py 

# after_success:
#   - coveralls

