language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - flake8 --exclude app/dbmodels --exclude fill_db.py app
  - flake8 run.py

script:
  - python3 run.py & 
  - python3 -m nose --with-coverage --cover-branches -v --cover-erase
  - coverage report -m --fail-under=10

after_success:
  - coveralls

branches:
  only:
- master
