language: python
python:
  - "3.6"

install:
  - pip3 install --upgrade setuptools
  - pip3 install -r requirements.txt
  - pip3 install coveralls==1.7.0
  - pip3 install nose==1.3.7
  - pip3 install flake8==3.7.7

before_script:
  #  - flake8 --exclude app/dbmodels --exclude fill_db.py app
  - flake8 pythonutils --exit-zero

script:
  - python3 -m unittest -v tests/test_simple.py 
  - python3 -m nose --with-coverage --cover-branches -v --cover-erase
  - coverage report -m --fail-under=10

after_success:
  - coveralls
  - coverage report -m

